### ISSUE TITLE
Histogrammer

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/AgentsPy#10]
Gør det muligt at lave simple histogrammer, både for kategoriske variabler ("infected", "immune", etc.) og for numeriske værdier (med mulighed for angivelse af binsize)

**Comment by JensKanstrupLarsen** [comment]
Histogrammer med kategorier findes nu. Bins er lidt sværere at lave uden at gøre det mere afhængigt af agenterne, men det kan nok lade sig gøre.

**Comment by JensKanstrupLarsen** [comment]
Bins er nu tilføjet, se de senere versioner af `stupid.py`.

**Comment by dybber** [comment]
Som jeg skrev et andet sted i går, så synes jeg det er lidt bøvlet at man skal skrive intervallerne op for sit histogram i stedet for at den selv opdeler det. Kan man ikke gøre det simplere?

**Comment by JensKanstrupLarsen** [comment]
Signaturen for `histogram_bins` er nu ændret fra
`histogram_bins(variable,bins,color)`
til
`histogram_bins(variable,minimum,maximum,bins,color)`
hvor `bins` i sidstnævnte er antallet af intervaller mellem `minimum` og `maximum`.
