### ISSUE TITLE
Udvid epidemi-model, så agenter forsøger at holde afstand

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/AgentsPy#11]
De skal ikke garantere afstand, men bare forsøge at gå i en retning, hvor de regner med mindst sandsynligt at støde på andre agenter.

**Comment by JensKanstrupLarsen** [comment]
Alle agenter i epidemi-modellen undviger nu syge agenter (syge agenter undviger også andre syge agenter). Det er dog ikke helt fejlfrit, da afstandsberegningen ikke kan ske helt korrekt med den torodiale simulations-flade (så de registrerer f.eks. ikke en syg agent, der står tæt på den anden side af simulations-fladen).

**Comment by dybber** [comment]
Det er lidt kringlet skrevet, så jeg genåbner lige med nogle kommentarer til hvordan vi kan gøre det lettere at forstå.

Jeg prøver først lige at forklare hvordan jeg forstår koden til at holde afstand, her i epidemic.py: https://github.com/DatalogiForAlle/pyagents/blob/master/epidemic.py#L32

For at holde afstand gør en agent følgende:
 - Finder sine naboer i en radius af 60 pixels
 - Tæller antallet af inficered naboer (nearby_infected)
 - Hver nabo har en vinkel, du finder gennemsnittet af de vinkler
 - Du peger modsat den gennemsnitlige vinkel

Feedback:
 - måske brug "average_angle" i variabel navnet i stedet for bare "new_dir"?
 - måske skal vi have en funktion "direction_to" eller "angle_to", så man ikke behøver at ændre agentens retning for at aflæse vinklen til en anden agent?
 - måske kan du lave en liste af vinkler, og først bagefter beregne gennemsnittet af værdierne i listen (det vil jeg selvfølgelig helst gøre med en filter og et map, men måske er det for avanceret til gymnasieelever)
 - du ændrer direction allerede på første linje i step-funktionen, det vil være pænere at vente med at lave den ændring til else-gren på dit if statement ("if nearby_infected > 0")
 - hvad betyder det at en infection er andet end 0 og 1, hvorfor kan den ikke bare være en boolean? Den bruges måske også til at tælle hvor længe den har været syg, altså tælle ned til immunitet?

**Comment by dybber** [comment]
Måske skal hele beregningen af "average_angle" egentlig være sin selvstændige funktion på den måde kan du skrive det sådan:
 - find alle naboer
 - fjern alle dem der ikke er inficerede fra listen, så du har en liste af smittede
 - kald average_angle på listen af smittede
 - brug resultatet til beregne den nye vinkel

**Comment by JensKanstrupLarsen** [comment]
Jeg er enig i at der burde være en `direction_to` eller `angle_to`, jeg overvejede det faktisk, da jeg sad og arbejdede på det, men det endte så med at blive en smule "hacket" alligevel.

`infection` fungerer ganske rigtigt som en tæller, der bestemmer i hvor mange ticks endnu at en agent er syg. Man kunne selvfølgelig have både en boolean og en counter, men jeg føler godt, at man kan lave det på denne her måde, uden, at det bliver for kringlet.

**Comment by JensKanstrupLarsen** [comment]
Har skubbet nogle ændringer til `epidemic.py` baseret på feedback.
