### ISSUE TITLE
Feedback på kodestil

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/AgentsPy#19]
Hej Jens

Du får lige lidt generelle stil-kommentarer her, jeg har skrevet nogle enkelte andre kommentarer direkte ind som kommentarer på de relevante commits.

 - Hvorfor bruger du din egen RNG funktion, og ikke bare random.randrange(0, x)?
Jeg tænker RNG måske bare kan forvirre mere end det gavner, specielt hvis de på et senere tidspunkt skal bruge Python til noget andet - og også hvis vi gerne vil appelere til Python open source communitiet, og få nogle andre til at bidrage til projektet, så er det nok bedst at forsøge at holde en kodestil der matcher andres.

 - Hvorfor bruger du x**0.5 i stedet for math.sqrt(x), igen tænker jeg at bruge biblioteksfunktionen er mindre forvirrende i længden (fx hvis de skal bruge noget andet end Python)

 - Der er en masse småting, bl.a. med brug af mellemrum, for lange linjer, sammenligning med None i stedet for "is None", osv., der gør at hvis man bruger `flake8` til at tjekke ens kodestil, så får man en masse warnings. Prøv at installer flake8, stå i roden af repositoriet og kør flake8 uden argumenter.

**Comment by dybber** [comment]
Til det sidste, behøver du faktisk ikke at rette en del af problemerne manuelt. Der findes et værktøj "black", der automatisk formaterer koden, fx ved at indsætte mellemrum, linjeskift, slette trailing whitespace, opdele for lange linjer m.m. Det kunne du prøve at køre

**Comment by JensKanstrupLarsen** [comment]
God feedback, jeg er enig.

Har fjernet burgen af `RNG` og `**`, og erstattet det med `random.randint` og `math.sqrt`.

Har fikset koden sådan at `flake8` nu ikke giver nogen warnings på hverken kildekoden eller eksemplerne (kun på `__init__.py`, men det virker bedre at beholde den nuværende notation der).

**Comment by dybber** [comment]
Super, ser ud til at man kan få flake8 til at ignorere specifikke warnings ved at tilføje en # noqa: F401, F403 kommentar efter linjen, se her https://stackoverflow.com/a/60594391/496605 eller i dokumentationen https://flake8.pycqa.org/en/3.7.9/user/violations.html#in-line-ignoring-errors

**Comment by dybber** [comment]
`grep`'pede efter `RNG` i repositoriet, og kan se du mangler at ændre det i din tutorial

**Comment by dybber** [comment]
Jeg har rettet det sidste her, så flake8 nu ikke rapporterer flere problemer
