### ISSUE TITLE
Overfør modeller fra pygments-udgaven

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/AgentsPy#5]
- [x] Epidemi-model

- [x] Urban Sprawl model

- [x] StupidModel (gerne i alle forskellige stadier, opret mappe med de forskellige versioner)

**Comment by JensKanstrupLarsen** [comment]
Alle tre modeller er overført nu.
StupidModel kan nok i visse områder optimeres ved at tilføje nogle funktioner til agent biblioteket.
Pythonversionerne af StupidModel er heller ikke fuldstændig 1:1 med specifikationerne fra dokumentet, men det kan diskuteres om det er nødvendigt.

**Comment by dybber** [comment]
stupid15.py og stupid16.py er vinduet så stort at det ikke kan vises på min 24" skærm, er det meningen?

Det ser også ud at begge filer mangler filen "stupid.cell", som setup-funktionen leder efter:

```
Traceback (most recent call last):
  File "/Users/dpr964/Development/educational/pyagents/agents/ui.py", line 316, in <lambda>
    btn.clicked.connect(lambda x: button_spec.function(self.model))
  File "stupid15.py", line 76, in setup
    cell_data = open("stupid.cell","r")
FileNotFoundError: [Errno 2] No such file or directory: 'stupid.cell'
Abort trap: 6
```

**Comment by JensKanstrupLarsen** [comment]
Der er ikke rigtig nogen indbygget skalering af modellen, så den størrelse af tiles man angiver er også den størrelse, de vises med på skærmen. Jeg ved ikke om PyQt har en nem måde at justere det på.

`stupid.cell` kan genereres ved at køre `generate_cell.py`.
