### ISSUE TITLE
Discuss: We should discuss whether to represent the Tiles grid as a list of lists

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/AgentsPy#63]
Currently, there's a lot of indexing calculation, to work with indexes into the tiles array, perhaps it will be easier for beginners to work with a 2D array, that is a list of lists in Python.

Instead of 
`tile = model.tiles[(y % model.y_tiles) * model.x_tiles + x % model.x_tiles]` it would be much easier for the user, if he/she could just write:

`tile = model.tiles[y][x]`

It would however also require us overload lookups on lists, to add the extra modulus I guess. Let's discuss pros/cons.

**Comment by JensKanstrupLarsen** [comment]
If I recall correctly, `model.tiles` was originally (for a brief period of time, at least) a list of lists. I agree that it makes more sense for the user to access it in this manner.

Suppose we go back to this representation - what do we need to change then?

**Comment by JensKanstrupLarsen** [comment]
I remember now - you can't do this with a list of lists:
```
for t in model.tiles:
    # Do something for each tile
```
