### ISSUE TITLE
Discuss: What if agents could be added directly to a tile?

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/AgentsPy#64]
In stupid model, and perhaps other models, you want to add agents directly to a tile, instead of doing that, you currently have to:
 - find the tile, check if it's occupied (this is okay)
 - create a new agent (this is okay)
 - add the agent to the model
 - calculate the index of the tile, and move the agent there
 - call `center_in_tile` on the new agent

The last three steps could be done in one step, if users could add agents directly to tiles (which then again would add it to the model)? I don't know if this makes sense, but let's discuss and look at pros/cons.

**Comment by JensKanstrupLarsen** [comment]
The method `Agent.jump_to_tile` was added recently, and performs the `Agent.center_in_tile` as part of the call as well. If this method is used, you can do
```
# Obtain the tile t somehow
if len(t.get_current_agents()) == 0:
    new_agent = Agent()
    model.add_agent(new_agent)
    new_agent.jump_to_tile(t)
```
I think the above code is a reasonable length for adding an agent to a specific tile, but I suppose a method `Model.add_agent_to_tile()` could be nice to have.

**Comment by dybber** [comment]
Oh, yeah, my bad. I don't think add_agent_to_tile is necessary when we have the other two, sorry about that!
