### ISSUE TITLE
Make first write through of Danish documentation

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/AgentsPy#94]
- [x] Move epidemic tutorial from .tex to reStructuredText
- [x] Draft subpages and structure of the documentation
- [x] Translate introduction
- [x] Write "Get started" page
- [x] Test epidemic tutorial, and update with recent changes to model spec
- [x] Add images to epidemic tutorial

**Comment by JensKanstrupLarsen** [comment]
I think the last three points might be fixed in #102
