### ISSUE TITLE
Line chart med en linje per agent

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/AgentsPy#96]

**Comment by JensKanstrupLarsen** [comment]
Der er to problemer her:

1. Antallet af agenter er ikke kendt fra start af når grafen oprettes (med f.x. `model.add_agent_graph()`)
2. Så skal man gøre det dynamisk, hvilket vil sige enten at gentegne hele grafen i hvert step (hvilket bliver endnu mere ressourcekrævende end biblioteket allerede er) eller tildele hver agent sin egent linje og så give den ansvaret for at overføre data til grafen. Den sidste mulighed er nok smartest, men kræver at man lige tænker over opsætningen.
